package com.example.hevycompanion.generate

import android.app.Application
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue
import androidx.lifecycle.AndroidViewModel
import androidx.lifecycle.viewModelScope
import com.example.hevycompanion.BuildConfig
import com.example.hevycompanion.data.ExerciseTemplate
import com.example.hevycompanion.data.ExerciseTemplateRepo
import com.example.hevycompanion.data.HevyExerciseAttrMap
import com.example.hevycompanion.data.HevyExerciseAttrs
import com.example.hevycompanion.data.PostRoutinesRequestBody
import com.example.hevycompanion.data.PostRoutinesRequestExercise
import com.example.hevycompanion.data.PostRoutinesRequestRoutine
import com.example.hevycompanion.data.PostRoutinesRequestSet
import com.example.hevycompanion.data.RepRange
import com.example.hevycompanion.data.RoutineFolder
import com.example.hevycompanion.muscle.MuscleAssetMap
import kotlin.random.Random
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch

/**
 * State holder for the static "Generate Workout" flow.
 *
 * Screen state machine:
 *   Closed → MusclePicker → Result → Closed
 *
 * The same Hevy template catalog used by `BrowserViewModel` powers this
 * one — we just instantiate our own repo handle so the two view-models can
 * be `viewModel()`'d independently in `MainActivity`. The catalog itself is
 * disk-cached for 7 days so the second consumer doesn't double-fetch.
 */
class GeneratorViewModel(app: Application) : AndroidViewModel(app) {

    private val repo = ExerciseTemplateRepo(
        context = app,
        apiKey = BuildConfig.HEVY_PUBLIC_API_KEY,
    )
    private val routineRepo = RoutineRepo(apiKey = BuildConfig.HEVY_PUBLIC_API_KEY)
    private val prefs = GeneratorPrefs(app)

    /**
     * Bundled `{id → level/goal/category}` side table — resolved once per
     * VM instance. Drives the level & category filters in [WorkoutGenerator].
     * Read lazily so the (on-disk) asset load is off the UI thread's cold
     * start; memoized afterwards by [HevyExerciseAttrMap] itself.
     */
    private val attrsById: Map<String, HevyExerciseAttrs> by lazy { HevyExerciseAttrMap.all(app) }

    sealed class Screen {
        data object Closed : Screen()
        data object MusclePicker : Screen()
        data object Result : Screen()
        /** Pick a routine folder to save the generated workout into. */
        data object SaveFolderPick : Screen()
        /** Name + sets/reps/weight/rest overrides before POSTing. */
        data object SaveDetails : Screen()
    }

    var screen by mutableStateOf<Screen>(Screen.Closed)
        private set

    var templates by mutableStateOf<List<ExerciseTemplate>>(emptyList())
        private set
    var isLoading by mutableStateOf(false)
        private set
    var errorMessage by mutableStateOf<String?>(null)
        private set

    // Filter state
    var selectedMuscles by mutableStateOf<Set<String>>(emptySet())
        private set
    /**
     * User's equipment selection, persisted across app restarts via
     * [GeneratorPrefs]. First-open default is ALL known equipment (matches
     * Liftoff's "all 97/97" default); after that, whatever the user last
     * toggled in the picker wins on every subsequent launch.
     */
    var selectedEquipment by mutableStateOf(
        prefs.selectedEquipment ?: EquipmentMap.KNOWN_HEVY_TAGS.toSet()
    )
        private set
    /**
     * Multi-select exercise-level filter. Persisted; first-open default is
     * all three levels so the pool isn't narrowed before the user has
     * touched the filter.
     */
    var selectedLevels by mutableStateOf(prefs.selectedLevels ?: Level.DEFAULT)
        private set
    /**
     * Multi-select compound/isolation filter. Persisted; first-open default
     * is both categories (permissive).
     */
    var selectedCategories by mutableStateOf(prefs.selectedCategories ?: Category.DEFAULT)
        private set
    var duration by mutableStateOf(Duration.DEFAULT)
        private set
    /** Weight-bias (Light/Medium/Heavy). Persisted; default is HEAVY. */
    var weights by mutableStateOf(prefs.selectedWeights ?: Weights.DEFAULT)
        private set

    var generated by mutableStateOf<GeneratedWorkout?>(null)
        private set

    /**
     * Plain-language reason the result list is empty when the user just hit
     * Regenerate. Surfaced in [GenerateWorkoutScreen] above the (empty) result
     * list so beginners onboarded by the user don't sit there confused why
     * "no exercises" came back. Null = no warning to show.
     */
    val warningMessage: String?
        get() = when {
            selectedMuscles.isEmpty() -> "Pick at least one muscle to generate a workout."
            selectedEquipment.isEmpty() -> "All equipment is deselected — pick at least one to see exercises."
            selectedLevels.isEmpty() -> "All levels are deselected — pick at least one."
            selectedCategories.isEmpty() -> "All categories are deselected — pick at least one."
            else -> null
        }

    // ---- Save-routine flow state -------------------------------------------

    /** Null = not yet fetched; emptyList() = fetch completed and there are none. */
    var folders by mutableStateOf<List<RoutineFolder>?>(null)
        private set
    var isLoadingFolders by mutableStateOf(false)
        private set
    var folderError by mutableStateOf<String?>(null)
        private set

    /** The folder the user picked on the folder-pick screen. null = "My Routines" (default). */
    var chosenFolder by mutableStateOf<RoutineFolder?>(null)
        private set

    /**
     * Save-details form state — all mutable by the user, all prepopulated from
     * the generated workout when [enterSaveFolderPick] fires. Held as strings
     * so the TextFields don't jump to "0" when the user clears a digit; parsed
     * only at submit time.
     */
    var saveTitle by mutableStateOf("")
        private set
    var saveSetsText by mutableStateOf("")
        private set
    var saveRepsText by mutableStateOf("")
        private set
    /** Per-exercise weight overrides, one string per generated exercise, same order. */
    var saveWeightsText by mutableStateOf<List<String>>(emptyList())
        private set
    /** Total seconds = 90 (1m 30s) by default per the user's spec. */
    var saveRestSecondsText by mutableStateOf("90")
        private set

    var isSaving by mutableStateOf(false)
        private set
    var saveError by mutableStateOf<String?>(null)
        private set
    /** Transient "Saved ✓" flag; the Result screen shows a toast and resets it. */
    var saveSuccess by mutableStateOf(false)
        private set

    fun openPicker() {
        screen = Screen.MusclePicker
        ensureLoaded()
    }
    fun close() { screen = Screen.Closed }

    /** Called when the muscle picker's ✓ button is tapped. */
    fun confirmMuscles(muscles: Set<String>) {
        selectedMuscles = muscles
        screen = Screen.Result
        regenerate()
    }

    // Filter changes stash the new value but DON'T re-roll. Regeneration is
    // driven exclusively by the "Regenerate" button (plus the initial generation
    // after the muscle picker closes), so the user can tweak several filters
    // in a row and only pay the roll once. The currently-displayed workout
    // stays visible — staler than the chips above it — until they tap
    // Regenerate, which is the moment "the new selections are taken into
    // consideration".
    //
    // All of the multi-select filters (level / category / equipment) use an
    // instant-apply model: every tap in the picker flips the state here
    // directly, and the sheet can be dismissed at any time without losing
    // changes — same as how the single-select filters already behaved.
    fun pickDuration(d: Duration) { duration = d }
    fun pickWeights(w: Weights) {
        weights = w
        prefs.selectedWeights = w
    }
    fun pickEquipment(eq: Set<String>) {
        selectedEquipment = eq
        prefs.selectedEquipment = eq
    }
    fun toggleEquipment(tag: String) {
        val next = if (tag in selectedEquipment) selectedEquipment - tag else selectedEquipment + tag
        pickEquipment(next)
    }
    fun toggleLevel(lvl: Level) {
        val next = if (lvl in selectedLevels) selectedLevels - lvl else selectedLevels + lvl
        selectedLevels = next
        prefs.selectedLevels = next
    }
    fun toggleCategory(cat: Category) {
        val next = if (cat in selectedCategories) selectedCategories - cat else selectedCategories + cat
        selectedCategories = next
        prefs.selectedCategories = next
    }
    /**
     * Flip one muscle in the current selection, for the on-result-screen
     * muscle chip. Stashes only — the displayed workout doesn't re-roll
     * until the user taps Regenerate, same as every other filter. Unlike
     * [confirmMuscles] this does NOT change the screen state.
     *
     * Not persisted: muscles are a per-workout intent, and persisting them
     * would re-apply yesterday's selection on tomorrow's open (the initial
     * muscle-picker step would look pre-ticked with stale choices).
     */
    fun toggleMuscle(hevyMuscle: String) {
        val key = hevyMuscle.lowercase()
        selectedMuscles = if (key in selectedMuscles) selectedMuscles - key else selectedMuscles + key
    }

    /** Re-roll all exercises with the current filters. */
    fun regenerate() {
        if (selectedMuscles.isEmpty() || templates.isEmpty()) {
            generated = null
            return
        }
        generated = WorkoutGenerator.generate(
            templates = templates,
            attrsById = attrsById,
            selectedHevyMuscles = selectedMuscles,
            selectedEquipment = selectedEquipment,
            selectedLevels = selectedLevels,
            selectedCategories = selectedCategories,
            duration = duration,
            weights = weights,
            random = Random.Default,
        )
    }

    // ---- Save-routine flow --------------------------------------------------

    /**
     * Entered from the Save button on the Result screen. Seeds the overrides
     * from the generated workout, kicks off a folders fetch, transitions to
     * [Screen.SaveFolderPick].
     */
    fun enterSaveFolderPick() {
        val gen = generated ?: return
        saveTitle = defaultRoutineTitle()
        saveSetsText = gen.exercises.firstOrNull()?.sets?.toString() ?: "3"
        saveRepsText = gen.exercises.firstOrNull()?.reps?.toString() ?: "8"
        saveWeightsText = gen.exercises.map { formatWeightForEditor(it.weightKg) }
        saveRestSecondsText = "90"
        saveError = null
        saveSuccess = false
        chosenFolder = null
        screen = Screen.SaveFolderPick
        fetchFolders()
    }

    fun fetchFolders() {
        if (isLoadingFolders) return
        isLoadingFolders = true
        folderError = null
        viewModelScope.launch(Dispatchers.IO) {
            try {
                folders = routineRepo.fetchAllFolders()
            } catch (e: Exception) {
                folderError = e.message ?: "Could not load folders"
                folders = emptyList()
            } finally {
                isLoadingFolders = false
            }
        }
    }

    fun pickFolder(folder: RoutineFolder?) {
        chosenFolder = folder
        screen = Screen.SaveDetails
    }

    fun updateSaveTitle(v: String) { saveTitle = v }
    fun updateSaveSets(v: String) { saveSetsText = v.filter { it.isDigit() } }
    fun updateSaveReps(v: String) { saveRepsText = v.filter { it.isDigit() } }
    fun updateSaveWeight(index: Int, v: String) {
        // Allow digits + one decimal point; matches what the generator emits
        // for odd-multiplier weights (e.g. 11.25 kg dumbbell).
        val filtered = v.filter { it.isDigit() || it == '.' }
            .let { s -> if (s.count { it == '.' } > 1) s.dropLastWhile { it == '.' } else s }
        saveWeightsText = saveWeightsText.toMutableList().also { list ->
            if (index in list.indices) list[index] = filtered
        }
    }
    fun updateSaveRestSeconds(v: String) { saveRestSecondsText = v.filter { it.isDigit() } }

    fun backToFolderPick() {
        screen = Screen.SaveFolderPick
    }

    fun cancelSave() {
        screen = Screen.Result
        saveError = null
    }

    /**
     * POSTs the routine. On success, transitions back to Result and flips
     * [saveSuccess] so the screen can show a confirmation snackbar. On failure,
     * leaves the user on SaveDetails with an error string to display.
     */
    fun submitSave() {
        val gen = generated ?: return
        if (isSaving) return

        val title = saveTitle.trim()
        if (title.isEmpty()) { saveError = "Routine name can't be empty."; return }
        val sets = saveSetsText.toIntOrNull()?.takeIf { it > 0 }
            ?: run { saveError = "Sets must be a positive number."; return }
        val reps = saveRepsText.toIntOrNull()?.takeIf { it > 0 }
            ?: run { saveError = "Reps must be a positive number."; return }
        val rest = saveRestSecondsText.toIntOrNull()?.takeIf { it >= 0 }
            ?: run { saveError = "Rest seconds must be 0 or more."; return }
        val weights: List<Float?> = gen.exercises.mapIndexed { i, _ ->
            val raw = saveWeightsText.getOrNull(i).orEmpty().trim()
            if (raw.isEmpty() || raw == ".") null
            else raw.toFloatOrNull()
                ?: run { saveError = "Weight #${i + 1} is not a number."; return }
        }

        val body = PostRoutinesRequestBody(
            routine = PostRoutinesRequestRoutine(
                title = title,
                folderId = chosenFolder?.id,
                notes = "",
                exercises = gen.exercises.mapIndexed { i, ex ->
                    val wKg = weights[i]
                    PostRoutinesRequestExercise(
                        exerciseTemplateId = ex.template.id,
                        supersetId = null,
                        restSeconds = rest,
                        notes = null,
                        sets = List(sets) {
                            PostRoutinesRequestSet(
                                type = "normal",
                                weightKg = wKg,
                                reps = reps,
                                repRange = RepRange(start = reps, end = reps),
                            )
                        },
                    )
                },
            )
        )

        isSaving = true
        saveError = null
        viewModelScope.launch(Dispatchers.IO) {
            try {
                when (val result = routineRepo.createRoutine(body)) {
                    is CreateRoutineResult.Success -> {
                        saveSuccess = true
                        screen = Screen.Result
                    }
                    is CreateRoutineResult.RoutineLimitReached ->
                        saveError = "Routine limit reached — delete one in the source app and try again."
                    is CreateRoutineResult.InvalidBody ->
                        saveError = "Server rejected the request (400). ${result.body.take(200)}"
                    is CreateRoutineResult.HttpError ->
                        saveError = "Save failed (HTTP ${result.code}). ${result.body.take(200)}"
                }
            } catch (e: Exception) {
                saveError = "Could not reach the server: ${e.message}"
            } finally {
                isSaving = false
            }
        }
    }

    fun clearSaveSuccessFlag() { saveSuccess = false }

    /** Pretty default title from the chosen muscle set, e.g. "Chest, Shoulders Workout". */
    private fun defaultRoutineTitle(): String {
        if (selectedMuscles.isEmpty()) return "Generated Workout"
        return selectedMuscles
            .map { MuscleAssetMap.displayName(it) }
            .sorted()
            .joinToString(", ") + " Workout"
    }

    /** Locale-US numeric formatting for the editable weight field (no "kg" suffix). */
    private fun formatWeightForEditor(kg: Float): String {
        if (kg <= 0f) return ""
        return if (kg % 1f == 0f) kg.toInt().toString()
               else "%.2f".format(java.util.Locale.US, kg).trimEnd('0').trimEnd('.')
    }

    /** Swap one exercise (by index) for a different one from the same pool. */
    fun swapAt(index: Int) {
        val current = generated ?: return
        generated = WorkoutGenerator.swap(
            current = current,
            indexToSwap = index,
            templates = templates,
            attrsById = attrsById,
            selectedHevyMuscles = selectedMuscles,
            selectedEquipment = selectedEquipment,
            selectedLevels = selectedLevels,
            selectedCategories = selectedCategories,
            weights = weights,
            random = Random.Default,
        )
    }

    /** Loads the catalog from cache or the network on first open. */
    fun ensureLoaded() {
        if (templates.isNotEmpty() || isLoading) return
        repo.cached()?.let { templates = it; return }
        viewModelScope.launch(Dispatchers.IO) {
            isLoading = true
            errorMessage = null
            try {
                templates = repo.refresh()
                // If the user picked muscles before the network finished, generate now.
                if (screen is Screen.Result && selectedMuscles.isNotEmpty()) regenerate()
            } catch (e: Exception) {
                errorMessage = "Could not load exercises: ${e.message}"
            } finally {
                isLoading = false
            }
        }
    }
}
