package com.example.hevycompanion.generate.mm

import android.content.Context
import com.example.hevycompanion.util.GsonHolder
import com.google.gson.annotations.SerializedName
import com.google.gson.reflect.TypeToken

/**
 * A single exercise in the bundled M&M catalog.
 *
 * Fed by `companion/src/main/assets/mm_catalog_runtime.json`, generated by
 * `scripts/mm_scrape.py` from a one-shot mitmproxy capture of the M&M app's
 * authenticated `/api/v1/video_with_details/exercises` response. Field names
 * map 1:1 to the JSON keys the script emits — keep them in sync.
 *
 * Distinct from [com.example.hevycompanion.data.ExerciseTemplate]: this is a
 * separate data source feeding a separate generator, with much richer
 * taxonomy than Hevy's REST catalog (movement patterns, four muscle roles,
 * 19 sub-areas, 22 equipment types).
 */
data class MmExercise(
    val id: String,
    val name: String,
    /** "strength" / "bodyweight" / "time" — drives default sets/reps prescription. */
    val type: String?,
    @SerializedName("is_paid") val isPaid: Boolean,
    val category: String,
    val area: String,
    @SerializedName("sub_areas") val subAreas: List<String>,
    val equipment: List<String>,
    @SerializedName("movement_pattern") val movementPattern: List<String>,
    @SerializedName("target_muscles") val targetMuscles: List<String>,
    @SerializedName("synergist_muscles") val synergistMuscles: List<String>,
    @SerializedName("stabilizer_muscles") val stabilizerMuscles: List<String>,
    @SerializedName("default_workout_fields") val defaultWorkoutFields: List<String>,
    @SerializedName("thumbnail_url") val thumbnailUrl: String?,
    @SerializedName("video_url") val videoUrl: String?,
    @SerializedName("video_duration_sec") val videoDurationSec: Int?,
)

object MmCatalog {
    private const val ASSET_PATH = "mm_catalog_runtime.json"

    @Volatile private var cache: List<MmExercise>? = null

    fun all(context: Context): List<MmExercise> {
        cache?.let { return it }
        synchronized(this) {
            cache?.let { return it }
            val raw = context.assets.open(ASSET_PATH).bufferedReader().use { it.readText() }
            val type = object : TypeToken<List<MmExercise>>() {}.type
            val parsed: List<MmExercise> = GsonHolder.gson.fromJson(raw, type)
            cache = parsed
            return parsed
        }
    }

    /**
     * Background-prime the catalog so the first navigation to the M&M
     * generator screen doesn't block a compose frame on a 2 MB JSON parse.
     * Safe to call multiple times — subsequent calls return immediately
     * because [cache] is already populated.
     *
     * Call from [Application.onCreate] (or anywhere on a non-main dispatcher)
     * with `kotlinx.coroutines.GlobalScope.launch(Dispatchers.IO) { MmCatalog.preload(this@HevyApplication) }`
     * — wrapper provided in `MmCatalogPreloader.preload()` so callers don't
     * need to depend on coroutines from non-coroutine call sites.
     */
    fun preload(context: Context) {
        // Best-effort: swallow IO errors here so a missing asset can never
        // crash startup. The on-demand all() path will surface the failure
        // when the user actually navigates to the generator.
        runCatching { all(context) }
    }
}
