package com.example.hevycompanion.generate.mm

import android.app.Application
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue
import androidx.lifecycle.AndroidViewModel
import com.example.hevycompanion.muscle.LiftoffMuscleCard
import kotlin.random.Random

class MmGeneratorViewModel(app: Application) : AndroidViewModel(app) {

    private val prefs = MmGeneratorPrefs(app)

    sealed class Screen {
        data object Closed : Screen()
        data object Setup : Screen()
        data object Result : Screen()
    }

    var screen by mutableStateOf<Screen>(Screen.Closed)
        private set

    val catalog: List<MmExercise> by lazy { MmCatalog.all(getApplication()) }

    /** Distinct equipment values found in the bundled catalog, sorted. */
    val knownEquipment: List<String> by lazy {
        catalog.flatMap { it.equipment }.toSortedSet().toList()
    }

    /** Distinct sub-areas in the catalog (19 in M&M's taxonomy), sorted. */
    val knownSubAreas: List<String> by lazy {
        catalog.flatMap { it.subAreas }.toSortedSet().toList()
    }

    var modeKind by mutableStateOf(prefs.modeKind)
        private set
    var splitDay by mutableStateOf(prefs.splitDay ?: SplitDay.DEFAULT)
        private set
    var selectedSubAreas by mutableStateOf(prefs.subAreas ?: emptySet())
        private set
    var selectedEquipment by mutableStateOf(prefs.equipment ?: knownEquipment.toSet())
        private set
    var selectedTypes by mutableStateOf(prefs.types ?: ExerciseType.DEFAULT)
        private set
    var duration by mutableStateOf(MmDuration.DEFAULT)
        private set
    var addWarmup by mutableStateOf(prefs.addWarmup)
        private set
    var addCooldown by mutableStateOf(prefs.addCooldown)
        private set

    var generated by mutableStateOf<MmGeneratedWorkout?>(null)
        private set

    /** Mirrors GeneratorViewModel.warningMessage — surfaces "all-deselected"
     *  states so the result screen can explain an empty workout. */
    val warningMessage: String?
        get() = when {
            modeKind == MmGeneratorPrefs.MODE_SUB_AREAS && selectedSubAreas.isEmpty() ->
                "Pick at least one sub-area to generate a workout."
            selectedEquipment.isEmpty() ->
                "All equipment is deselected — pick at least one to see exercises."
            selectedTypes.isEmpty() ->
                "All exercise types are deselected — pick at least one."
            else -> null
        }

    fun open() { screen = Screen.Setup }
    fun close() { screen = Screen.Closed }

    fun pickModeKind(kind: String) {
        modeKind = kind
        prefs.modeKind = kind
    }
    fun pickSplitDay(day: SplitDay) {
        splitDay = day
        prefs.splitDay = day
    }
    fun toggleSubArea(area: String) {
        selectedSubAreas = if (area in selectedSubAreas) selectedSubAreas - area
                          else selectedSubAreas + area
        prefs.subAreas = selectedSubAreas
    }

    /**
     * Multi-select toggle for the Liftoff card grid in the "Pick muscles"
     * sub-mode. Mirrors `BrowserViewModel.onMuscleCardTap` for `Source.MM`:
     * cards with `mmSubAreas` toggle those entries (e.g. Quadriceps →
     * `Legs | Quads` + `Legs | Hip Flexors`); cards without sub-areas
     * (Upper/Lower Chest, since M&M's catalog has no `Chest | …` split)
     * toggle the area string.
     *
     * `Mode.SubAreas.matches` already accepts both via
     * `ex.area in selected || ex.subAreas.any { it in selected }`, so the
     * mixed set works directly without changing the algorithm.
     */
    fun onMuscleCardTap(card: LiftoffMuscleCard) {
        selectedSubAreas = if (card.mmSubAreas.isNotEmpty()) {
            val cardSubs = card.mmSubAreas.toSet()
            val allSelected = cardSubs.all { it in selectedSubAreas }
            if (allSelected) selectedSubAreas - cardSubs else selectedSubAreas + cardSubs
        } else {
            val area = card.mmAreaFallback
            if (area in selectedSubAreas) selectedSubAreas - area else selectedSubAreas + area
        }
        prefs.subAreas = selectedSubAreas
    }

    /**
     * Whether [card] is currently part of the muscle selection. Cards with
     * sub-areas count as selected when ALL of their sub-areas are present
     * (matches the toggle semantics in [onMuscleCardTap]); cards without
     * sub-areas count as selected when their area fallback is present.
     */
    fun isCardSelected(card: LiftoffMuscleCard): Boolean =
        if (card.mmSubAreas.isNotEmpty()) {
            card.mmSubAreas.all { it in selectedSubAreas }
        } else {
            card.mmAreaFallback in selectedSubAreas
        }
    fun toggleEquipment(eq: String) {
        selectedEquipment = if (eq in selectedEquipment) selectedEquipment - eq
                            else selectedEquipment + eq
        prefs.equipment = selectedEquipment
    }
    fun toggleType(t: ExerciseType) {
        selectedTypes = if (t in selectedTypes) selectedTypes - t else selectedTypes + t
        prefs.types = selectedTypes
    }
    fun pickDuration(d: MmDuration) { duration = d }
    fun toggleAddWarmup(v: Boolean) { addWarmup = v; prefs.addWarmup = v }
    fun toggleAddCooldown(v: Boolean) { addCooldown = v; prefs.addCooldown = v }

    fun generate() {
        val mode: Mode = when (modeKind) {
            MmGeneratorPrefs.MODE_SUB_AREAS -> Mode.SubAreas(selectedSubAreas)
            else -> Mode.Split(splitDay)
        }
        generated = MmGenerator.generate(
            catalog = catalog,
            mode = mode,
            equipment = selectedEquipment,
            types = selectedTypes,
            duration = duration,
            addWarmup = addWarmup,
            addCooldown = addCooldown,
            random = Random.Default,
        )
        screen = Screen.Result
    }

    fun regenerate() = generate()

    fun swapAt(index: Int) {
        val current = generated ?: return
        val mode: Mode = when (modeKind) {
            MmGeneratorPrefs.MODE_SUB_AREAS -> Mode.SubAreas(selectedSubAreas)
            else -> Mode.Split(splitDay)
        }
        generated = MmGenerator.swap(
            current = current,
            indexToSwap = index,
            catalog = catalog,
            mode = mode,
            equipment = selectedEquipment,
            types = selectedTypes,
            duration = duration,
            random = Random.Default,
        )
    }

    fun backToSetup() { screen = Screen.Setup }
}
